services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9999:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - '3333:3000'
    depends_on:
      - prometheus
    restart: always

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100

  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: always

  nginx:
    image: nginx
    container_name: nginx-www
    volumes:
      - ./nginx/html:/usr/share/nginx/html:rw
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - '7000:80'
    restart: always

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    env_file:
      - .env
    command:
      - -nginx.scrape-uri=http://nginx/stub_status
    expose:
      - 9113
    depends_on:
      - prometheus
