global:
 scrape_interval: 15s
scrape_configs:
 - job_name: "prometheus"
   static_configs:
     - targets: ["node-exporter:9100"]

 - job_name: "prometheus-exporter"
   static_configs:
     - targets: ["nginx-prometheus-exporter:9113"]

rule_files:
 - alert_rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
